# Generated by Django 2.0.6 on 2020-11-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201101_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tuser',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
