# Generated by Django 2.0.6 on 2020-11-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201101_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
